[v15.0.5]: Backport upstream 13856 - reshard state check fix
slackhq/vitess pull request #322
Opened 2024-04-30 19:45 UTC by tanjinx

## Description

backport https://github.com/vitessio/vitess/pull/13856
fixing confusing resharding message https://jira.tinyspeck.com/browse/DRE-9167

```
Fatal MySQL error: DB-vitess: ERUnknownError 1105 target: pool1.-80.primary: current keyspace is being resharded
```

v14.0.5 backport https://github.com/slackhq/vitess/pull/321

## Related Issue(s)

## Checklist

-   [ ] "Backport to:" labels have been added if this change should be back-ported
-   [ ] Tests were added or are not required
-   [ ] Did the new or modified tests pass consistently locally and on the CI
-   [ ] Documentation was added or is not required

## Deployment Notes

2024-05-04 01:00 UTC, vmogilev approved these changes

2024-05-04 12:04 UTC, timvaillancourt commented
@tanjinx this PR is including the git state of the upstream PR

How did you do the backport and is it possible to use `git cherry-pick -m 1 <merge SHA>` so we keep v15 consistent with git history?

2024-05-04 12:05 UTC, timvaillancourt requested changes
Left comment about git history/backport method

2024-05-28 19:07 UTC, timvaillancourt commented
Replacing this with https://github.com/slackhq/vitess/pull/377 which uses `git cherry-pick`

2024-05-28 19:07 UTC, closed without merging